CREATE DATABASE Lab2;

USE Lab2;

CREATE TABLE Region (
    RegionID SMALLINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Role (
    RoleID SMALLINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(30) NOT NULL
);

CREATE TABLE [User] (
    UserID SMALLINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    RegionID SMALLINT NOT NULL,
    LinkAvatar NVARCHAR(255),
    IsDeleted BIT DEFAULT(0),
    RoleID SMALLINT NOT NULL,
    OTP VARCHAR(6),

    CONSTRAINT FK_User_Region 
        FOREIGN KEY (RegionID) REFERENCES Region(RegionID),

    CONSTRAINT FK_User_Role
        FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

CREATE TABLE GameLevel (
    LevelID SMALLINT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255)
);

CREATE TABLE Question (
    QuestionID SMALLINT PRIMARY KEY IDENTITY(1,1),
    ContentQuestion NVARCHAR(255) NOT NULL,
    Answer NVARCHAR(255) NOT NULL,
    Option1 NVARCHAR(255),
    Option2 NVARCHAR(255),
    Option3 NVARCHAR(255),
    Option4 NVARCHAR(255),
    LevelID SMALLINT NOT NULL,

    CONSTRAINT FK_Question_Level
        FOREIGN KEY (LevelID) REFERENCES GameLevel(LevelID)
);

CREATE TABLE LevelResult (
    QuizResultID SMALLINT PRIMARY KEY IDENTITY(1,1),
    UserID SMALLINT NOT NULL,
    LevelID SMALLINT NOT NULL,
    Score INT,
    CompletionDate DATE DEFAULT GETDATE(),

    CONSTRAINT FK_LevelResult_User
        FOREIGN KEY (UserID) REFERENCES [User](UserID),

    CONSTRAINT FK_LevelResult_Level
        FOREIGN KEY (LevelID) REFERENCES GameLevel(LevelID)
);
GO
